import { analyzeMarketStructure, detectFairValueGaps } from '../types/analysis.js';
import type { StrategyAnalyzer, StrategyContext, StrategyResult } from '../types/strategies.js';

const result = (strategy: string, conditions: Record<string, boolean>, evidence: string[], direction?: 'bullish' | 'bearish'): StrategyResult => { const validSetup = Object.values(conditions).every(Boolean); return { strategy, validSetup, setupStage: validSetup ? 'confirmed_conditions' : 'NO VALID SETUP', conditions, ...(direction ? { direction } : {}), evidence, limitations: ['Heuristic interpretation; not a prediction or execution instruction.'] }; };
export const ictAnalyzer: StrategyAnalyzer = { name: 'ICT-inspired', analyze: (context) => { const sweep = context.sweeps.at(-1); const displacement = context.displacements.at(-1); const fvg = context.fvgs.at(-1); const direction = sweep?.direction; return result('ICT-inspired', { liquiditySweep: Boolean(sweep), displacement: Boolean(displacement?.detected), marketStructureShift: context.structure.events.some((event) => event.type === 'MSS'), fairValueGap: Boolean(fvg), retracement: false }, ['Conditions are reported independently; retracement is deliberately not inferred.', 'Related concepts: FVG, order-block candidate, breaker/inversion-FVG candidate, premium/discount, liquidity sweep, and MSS.'], direction); } };
export const crtAnalyzer: StrategyAnalyzer = { name: 'CRT-inspired', analyze: (context) => { const prior = context.candles.at(-2); const current = context.candles.at(-1); const expansion = Boolean(prior && current && (current.high > prior.high || current.low < prior.low)); const reclaim = Boolean(prior && current && current.close <= prior.high && current.close >= prior.low); return result('CRT-inspired', { definedRange: Boolean(prior), expansion, reclaimOrReversal: reclaim, confirmation: expansion && reclaim }, ['CRT requires a defined prior range, an expansion, and a reclaim/reversal confirmation.']); } };
export const turtleSoupAnalyzer: StrategyAnalyzer = { name: 'Turtle Soup', analyze: (context) => { const prior = context.candles.slice(-6, -1); const current = context.candles.at(-1); const high = Math.max(...prior.map((candle) => candle.high)); const low = Math.min(...prior.map((candle) => candle.low)); const failedHigh = Boolean(current && current.high > high && current.close < high); const failedLow = Boolean(current && current.low < low && current.close > low); return result('Turtle Soup', { priorLevel: prior.length > 0, breakBeyondLevel: failedHigh || failedLow, failureToSustain: failedHigh || failedLow, returnInsideRange: failedHigh || failedLow, confirmation: false }, ['Confirmation remains false until a separate rule confirms the reversal.'], failedHigh ? 'bearish' : failedLow ? 'bullish' : undefined); } };
export const priceActionAnalyzer: StrategyAnalyzer = { name: 'Price-action patterns', analyze: (context) => { const detected = context.patterns.filter((pattern) => pattern.detected); const bullish = detected.filter((pattern) => pattern.direction === 'bullish').length; const bearish = detected.filter((pattern) => pattern.direction === 'bearish').length; return result('Price-action patterns', { patternDetected: detected.length > 0, directionalAgreement: bullish > 0 || bearish > 0 }, detected.map((pattern) => `${pattern.name}: ${pattern.direction ?? 'neutral'}`), bullish > bearish ? 'bullish' : bearish > bullish ? 'bearish' : undefined); } };
export const conceptFamilyAnalyzer: StrategyAnalyzer = { name: 'Market-concept families', analyze: (context) => { const detected = context.conceptObservations.filter((observation) => observation.detected); return result('Market-concept families', { liquidityEvent: Boolean(context.sweeps.at(-1)), structureEvent: context.structure.events.length > 0, imbalance: context.fvgs.length > 0, zoneCandidate: context.zones.length > 0, conceptObservation: detected.length > 0 }, [...detected.map((observation) => `${observation.name}: ${observation.direction ?? 'neutral'}`), ...context.zones.slice(-5).map((zone) => `${zone.name}: ${zone.low}-${zone.high} (${zone.mitigated ? 'mitigated' : 'unmitigated'})`), 'SMT is only considered detected when a synchronized comparison instrument is supplied.']); } };
export function createStrategyContext(candles: StrategyContext['candles']): StrategyContext { const structure = analyzeMarketStructure(candles); return { candles, structure, sweeps: [], displacements: [], fvgs: detectFairValueGaps(candles), patterns: [], concepts: {}, conceptObservations: [], zones: [] }; }
export const strategyRegistry = [ictAnalyzer, crtAnalyzer, turtleSoupAnalyzer, priceActionAnalyzer, conceptFamilyAnalyzer];
