import { McpServer } from '@modelcontextprotocol/server';
import { z } from 'zod';
import type { BybitMarketClient } from './bybit/rest.js';
import type { Config } from './config.js';
import type { Logger } from './logger.js';
import { analyzeMarketStructure, detectFairValueGaps } from './types/analysis.js';
import { calculateRisk } from './types/risk.js';
import { intervals } from './types/market.js';
import { detectEqualLevels, detectLiquiditySweeps } from './analysis/liquidity.js';
import { detectDisplacement } from './analysis/displacement.js';
import { detectCandlestickPatterns, detectChartPatterns } from './analysis/patterns.js';
import { buildAnalysisContext } from './analysis/context.js';
import { strategyRegistry } from './strategies/registry.js';
import { evaluateTradeSignal } from './analysis/tradeSignal.js';
import { scorePair } from './scanner/scorer.js';

const category = z.enum(['spot', 'linear', 'inverse', 'option']).default('linear');
const symbol = z.string().regex(/^[A-Z0-9]+$/).default('NEARUSDT');
const interval = z.enum(intervals);
const json = (value: unknown) => ({ content: [{ type: 'text' as const, text: JSON.stringify(value, null, 2) }] });

export function createMcpServer(client: BybitMarketClient, config: Config, logger: Logger) {
  const server = new McpServer({ name: config.MCP_SERVER_NAME, version: '0.1.0' });
  server.registerTool('get_current_price', { description: 'Get current Bybit ticker data with freshness metadata.', inputSchema: z.object({ symbol, category }) }, async (input) => { logger.info('MCP tool invocation', { tool: 'get_current_price', symbol: input.symbol }); return json(await client.getTicker(input.symbol, input.category)); });
  server.registerTool('get_ohlcv', { description: 'Get a bounded chronological OHLCV sample; unfinished latest candles are marked.', inputSchema: z.object({ symbol, category, interval, limit: z.number().int().min(1).max(200).default(50) }) }, async (input) => { const candles = await client.getKlines(input.symbol, input.category, input.interval, input.limit); return json({ symbol: input.symbol, interval: input.interval, count: candles.length, latest: candles.at(-1), earliest: candles[0], candles: candles.slice(-50) }); });
  server.registerTool('get_multi_timeframe_data', { description: 'Get compact separated OHLCV summaries for multiple timeframes. Use analyze_market for derived concepts.', inputSchema: z.object({ symbol, category, timeframes: z.array(interval).min(1).max(8), candlesPerTimeframe: z.number().int().min(20).max(200).default(60) }) }, async (input) => { const datasets = await Promise.all(input.timeframes.map(async (timeframe) => { const candles = await client.getKlines(input.symbol, input.category, timeframe, input.candlesPerTimeframe); return [timeframe, { count: candles.length, latest: candles.at(-1), range: { high: Math.max(...candles.map((candle) => candle.high)), low: Math.min(...candles.map((candle) => candle.low)) }, structure: analyzeMarketStructure(candles), patterns: [...detectCandlestickPatterns(candles), ...detectChartPatterns(candles)].filter((pattern) => pattern.detected) }] as const; })); return json({ symbol: input.symbol, timeframes: Object.fromEntries(datasets) }); });
  server.registerTool('get_orderbook', { description: 'Get normalized Bybit order book levels.', inputSchema: z.object({ symbol, category, depth: z.number().int().min(1).max(1000).default(25) }) }, async (input) => json(await client.getOrderbook(input.symbol, input.category, input.depth)));
  server.registerTool('get_recent_trades', { description: 'Get normalized recent public trades.', inputSchema: z.object({ symbol, category, limit: z.number().int().min(1).max(1000).default(50) }) }, async (input) => json(await client.getRecentTrades(input.symbol, input.category, input.limit)));
  server.registerTool('get_funding_rate', { description: 'Get the current public funding rate where supported.', inputSchema: z.object({ symbol, category: z.enum(['linear', 'inverse']).default('linear') }) }, async (input) => json(await client.getFundingRate(input.symbol, input.category)));
  server.registerTool('get_open_interest', { description: 'Get public open-interest history.', inputSchema: z.object({ symbol, category: z.enum(['linear', 'inverse']).default('linear'), interval: z.enum(['5min', '15min', '30min', '1h', '4h', '1d']).default('1h'), limit: z.number().int().min(1).max(200).default(50) }) }, async (input) => json(await client.getOpenInterest(input.symbol, input.category, input.interval, input.limit)));
  server.registerTool('get_market_summary', { description: 'Get a compact ticker, volatility, funding, and open-interest market summary.', inputSchema: z.object({ symbol, category }) }, async (input) => { const [ticker, candles] = await Promise.all([client.getTicker(input.symbol, input.category), client.getKlines(input.symbol, input.category, '60', 30)]); const returns = candles.slice(1).map((candle, index) => Math.abs(candle.close / (candles[index]?.close ?? candle.close) - 1)); const volatility = returns.length ? returns.reduce((sum, value) => sum + value, 0) / returns.length : 0; return json({ symbol: input.symbol, ticker, recentVolatility: volatility, marketState: ticker.freshness.stale ? 'stale-data' : 'live-observation', candleStatus: candles.at(-1)?.closed ? 'closed' : 'unfinished' }); });
  server.registerTool('analyze_structure', { description: 'Calculate deterministic market structure, candidate liquidity, sweeps, displacement, and FVGs from supplied Bybit candles.', inputSchema: z.object({ symbol, category, interval, limit: z.number().int().min(20).max(500).default(200), lookback: z.number().int().min(1).max(20).default(3) }) }, async (input) => { const candles = await client.getKlines(input.symbol, input.category, input.interval, input.limit); const levels = detectEqualLevels(candles); const structure = analyzeMarketStructure(candles, input.lookback); return json({ symbol: input.symbol, interval: input.interval, structure, liquidity: levels, sweeps: detectLiquiditySweeps(candles, levels), displacement: detectDisplacement(candles), fairValueGaps: detectFairValueGaps(candles) }); });
  server.registerTool('calculate_risk', { description: 'Calculate deterministic position sizing; leverage changes margin, not underlying risk.', inputSchema: z.object({ accountBalance: z.number().positive(), riskPercent: z.number().positive().max(100), entry: z.number().positive(), stopLoss: z.number().positive(), takeProfit: z.number().positive(), leverage: z.number().positive().optional() }) }, async (input) => json(calculateRisk(input.accountBalance, input.riskPercent, input.entry, input.stopLoss, input.takeProfit, input.leverage)));
  server.registerTool('analyze_strategies', { description: 'Evaluate ICT, CRT, Turtle Soup, price-action patterns, and market-concept families with compact evidence. Incomplete conditions are NO VALID SETUP.', inputSchema: z.object({ symbol, category, interval, limit: z.number().int().min(20).max(300).default(120), correlatedSymbol: z.string().regex(/^[A-Z0-9]+$/).optional() }) }, async (input) => { const candles = await client.getKlines(input.symbol, input.category, input.interval, input.limit); const comparison = input.correlatedSymbol ? await client.getKlines(input.correlatedSymbol, input.category, input.interval, input.limit) : []; const context = buildAnalysisContext(candles, comparison); return json({ symbol: input.symbol, interval: input.interval, correlatedSymbol: input.correlatedSymbol, candleStatus: candles.at(-1)?.closed ? 'closed' : 'unfinished', latest: candles.at(-1), detectedConcepts: context.conceptObservations.filter((observation) => observation.detected), zones: context.zones.slice(-12), results: strategyRegistry.map((strategy) => strategy.analyze(context)) }); });
  server.registerTool('get_trade_signal', { description: 'Evaluate conservative analysis-only LONG, SHORT, or WAIT signals from closed-candle multi-timeframe structure, strategy evidence, entry zones, invalidation, and targets. Never places orders.', inputSchema: z.object({ symbol, category, timeframes: z.array(interval).min(2).max(8).default(['240', '60', '15']), candlesPerTimeframe: z.number().int().min(20).max(300).default(120), minConfluenceScore: z.number().int().min(2).max(8).default(2) }) }, async (input) => { const timeframeResults = await Promise.all(input.timeframes.map(async (timeframe) => { const candles = await client.getKlines(input.symbol, input.category, timeframe, input.candlesPerTimeframe); const analysisCandles = candles.at(-1)?.closed === false ? candles.slice(0, -1) : candles; const context = buildAnalysisContext(analysisCandles); const strategyResults = strategyRegistry.map((strategy) => strategy.analyze(context)); return { timeframe, latestCandleTimestamp: analysisCandles.at(-1)?.timestamp ?? 0, context, strategyResults }; })); const candidates = scorePair(input.symbol, timeframeResults, input.minConfluenceScore); const signals = candidates.map((candidate) => { const triggerResult = timeframeResults.filter((result) => candidate.confirmingTimeframes.some((confirmation) => confirmation.timeframe === result.timeframe)).at(-1); return triggerResult ? evaluateTradeSignal(input.symbol, candidate.direction, triggerResult.context, candidate.confirmingTimeframes.map((confirmation) => confirmation.timeframe), triggerResult.strategyResults) : null; }).filter((signal) => signal !== null); return json({ signals, candidates, timeframes: input.timeframes }); });
  return server;
}
